import { Service } from '../types';

export const SERVICES: Service[] = [
    // ── LASER TREATMENTS ──────────────────────────────────────────────────────
    {
        id: 'lhr-lip',
        name: 'Laser – Upper Lip',
        category: 'Laser Treatments',
        description: 'Precise diode laser targeting the upper lip for a permanently smooth finish. Fast 10-minute session with integrated cryo-cooling.',
        price: '$35',
        duration: '10 mins',
        benefits: ['Permanent Results', 'Pain-Free Cooling', 'All Skin Types'],
        image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80&auto=format&fit=crop',
        isPopular: false,
    },
    {
        id: 'lhr-underarm',
        name: 'Laser – Under Arm',
        category: 'Laser Treatments',
        description: 'Eliminate underarm hair permanently with our medical-grade diode laser. Smooth, odour-reduced skin in as few as 6 sessions.',
        price: '$35',
        duration: '15 mins',
        benefits: ['Permanent Hair-Free', 'Reduces Odour', 'Quick Session'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
        isPopular: false,
    },
    {
        id: 'lhr-full-face',
        name: 'Laser – Full Face',
        category: 'Laser Treatments',
        description: 'Complete facial laser hair removal covering cheeks, chin, upper lip, and sideburns. FDA-approved technology for all skin tones.',
        price: '$120',
        duration: '30 mins',
        benefits: ['Full Face Coverage', 'FDA-Approved', 'Long-Lasting'],
        image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=600&q=80&auto=format&fit=crop',
        isPopular: true,
        badge: 'Popular',
    },
    {
        id: 'lhr-brazilian',
        name: 'Laser – Brazilian',
        category: 'Laser Treatments',
        description: 'Full Brazilian laser hair removal with privacy, precision, and clinical comfort. Our most-requested intimate-area treatment.',
        price: '$129.99',
        duration: '30 mins',
        benefits: ['Complete Coverage', 'Discreet & Private', 'Medical-Grade Safety'],
        image: 'https://images.unsplash.com/photo-1532274402911-5a369e4c4bb5?w=600&q=80&auto=format&fit=crop',
        isPopular: true,
        badge: 'Bestseller',
    },
    {
        id: 'lhr-full-body',
        name: 'Laser – Full Body',
        category: 'Laser Treatments',
        description: 'The ultimate hair-free body transformation. All areas treated in a single session with our high-speed diode laser system.',
        price: '$599.99',
        duration: '90 mins',
        benefits: ['Complete Body', 'Single Session', 'Maximum Savings'],
        image: 'https://images.unsplash.com/photo-1519824145371-296894a0daa9?w=600&q=80&auto=format&fit=crop',
        isPopular: false,
        badge: 'Best Value',
    },

    // ── FACIAL RITUALS ────────────────────────────────────────────────────────
    {
        id: 'facial-hydra',
        name: 'Signature HydraFacial',
        category: 'Facial Rituals',
        description: 'Multi-step vortex cleanse, exfoliation, extraction, and hydration infusion. Instant glow with zero downtime.',
        price: '$195',
        duration: '60 mins',
        benefits: ['Instant Glow', 'Deep Hydration', 'Pore Refinement'],
        image: 'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600&q=80&auto=format&fit=crop',
        isPopular: true,
        badge: 'Signature',
    },
    {
        id: 'facial-cleansing',
        name: 'Deep Face Cleansing',
        category: 'Facial Rituals',
        description: 'Thorough cleanse, steam, manual extraction, and a customized masque to leave your skin balanced and refreshed.',
        price: '$40',
        duration: '45 mins',
        benefits: ['Removes Impurities', 'Clears Pores', 'Balanced Skin'],
        image: 'https://images.unsplash.com/photo-1556228720-da8e3810ee7f?w=600&q=80&auto=format&fit=crop',
        isPopular: false,
    },
    {
        id: 'facial-microderm',
        name: 'Microdermabrasion',
        category: 'Facial Rituals',
        description: 'Crystal-free diamond-tip resurfacing that polishes away dull skin layers to reveal a smoother, more luminous complexion.',
        price: '$85',
        duration: '50 mins',
        benefits: ['Skin Polishing', 'Texture Improvement', 'Brightening'],
        image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=600&q=80&auto=format&fit=crop',
        isPopular: false,
    },
    {
        id: 'facial-dermaplane',
        name: 'Dermaplaning',
        category: 'Facial Rituals',
        description: 'Gentle surgical blade exfoliation removing peach fuzz and dead skin cells for an ultra-smooth, luminous surface.',
        price: '$75',
        duration: '45 mins',
        benefits: ['Vellus Hair Removal', 'Silky Smooth', 'Better Product Absorption'],
        image: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&q=80&auto=format&fit=crop',
        isPopular: false,
    },
    {
        id: 'facial-custom',
        name: 'Custom Ritual Facial',
        category: 'Facial Rituals',
        description: 'A bespoke facial curated for your skin type — combining the best of clinical actives and sensory rituals.',
        price: '$110',
        duration: '60 mins',
        benefits: ['Personalized Formula', 'Clinical Actives', 'Deeply Relaxing'],
        image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80&auto=format&fit=crop',
        isPopular: false,
    },

    // ── CLINICAL CARE ─────────────────────────────────────────────────────────
    {
        id: 'clinical-peel',
        name: 'Medical Peel',
        category: 'Clinical Care',
        description: 'Professional-grade chemical exfoliation accelerating cellular turnover to reveal fresh, radiant skin and treat pigmentation.',
        price: '$120',
        duration: '45 mins',
        benefits: ['Deep Exfoliation', 'Acne Control', 'Brightening'],
        image: 'https://images.unsplash.com/photo-1576426863848-c21f53c60b19?w=600&q=80&auto=format&fit=crop',
        isPopular: false,
    },
    {
        id: 'clinical-microneedle',
        name: 'Micro-Needling',
        category: 'Clinical Care',
        description: 'Collagen-induction therapy using precision micro-channels to activate your skin\'s natural repair cascade. Addresses scars, fine lines, and laxity.',
        price: '$175',
        duration: '75 mins',
        benefits: ['Collagen Induction', 'Scar Reduction', 'Anti-Ageing'],
        image: 'https://images.unsplash.com/photo-1616391182219-e080b4d1043a?w=600&q=80&auto=format&fit=crop',
        isPopular: true,
        badge: 'Anti-Ageing',
    },
    {
        id: 'clinical-dermal-rejuv',
        name: 'Dermal Rejuvenation',
        category: 'Clinical Care',
        description: 'Targeted bio-stimulation therapy to repair skin texture, reduce hyperpigmentation, and achieve an even, healthy tone.',
        price: '$250',
        duration: '75 mins',
        benefits: ['Texture Repair', 'Even Skin Tone', 'Radiance Boost'],
        image: 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600&q=80&auto=format&fit=crop',
        isPopular: false,
    },

    // ── WAXING ────────────────────────────────────────────────────────────────
    {
        id: 'wax-brazilian',
        name: 'Brazilian Wax',
        category: 'Waxing',
        description: 'Full Brazilian waxing using premium hard wax for gentle, effective hair removal. Long-lasting smoothness for up to 6 weeks.',
        price: '$55',
        duration: '30 mins',
        benefits: ['6-Week Results', 'Hard Wax Formula', 'Sensitive-Skin Safe'],
        image: 'https://images.unsplash.com/photo-1487412840181-b39ce5fa3ac9?w=600&q=80&auto=format&fit=crop',
        isPopular: false,
    },
    {
        id: 'wax-full-leg',
        name: 'Full Leg Wax',
        category: 'Waxing',
        description: 'Complete full-leg waxing from ankle to upper thigh. Smooth, silky results that last weeks longer than shaving.',
        price: '$65',
        duration: '45 mins',
        benefits: ['Complete Coverage', 'Finer Regrowth', 'Silky Finish'],
        image: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=600&q=80&auto=format&fit=crop',
        isPopular: false,
    },

    // ── PACKAGES ──────────────────────────────────────────────────────────────
    {
        id: 'pkg-radiance',
        name: 'The Radiance Pack',
        category: 'Packages',
        description: 'Face + Neck laser package — our most popular bundle combining full-face and neck laser hair removal in one seamless appointment.',
        price: '$249.99',
        duration: '60 mins',
        benefits: ['Face + Neck Combo', 'Save $300 on 6-course', 'Priority Scheduling'],
        image: 'https://images.unsplash.com/photo-1554188248-986adbb73be4?w=600&q=80&auto=format&fit=crop',
        isPopular: true,
        badge: 'Best Bundle',
    },
    {
        id: 'pkg-transformation',
        name: 'Full Transformation',
        category: 'Packages',
        description: 'Complete laser hair removal across all body zones. The most comprehensive package for total transformation and maximum value.',
        price: '$499.99',
        duration: '120 mins',
        benefits: ['All Body Zones', 'Save $500 on 6-course', 'Exclusive VIP Access'],
        image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80&auto=format&fit=crop&crop=top',
        isPopular: false,
        badge: 'VIP',
    },
];

export const WHATSAPP_NUMBER = '16478904871'; // Client's updated WhatsApp number
