import { Service } from '../types';

export const SERVICES: Service[] = [

    // ── THREADING ──────────────────────────────────────────────────────────────
    {
        id: 'thread-eyebrow',
        name: 'Eyebrow Threading',
        category: 'Threading',
        description: 'Precise eyebrow shaping using traditional threading for clean, defined brows.',
        price: '$12',
        duration: '10 mins',
        benefits: ['Clean Shape', 'Long-Lasting', 'No Chemicals'],
        image: 'https://images.unsplash.com/photo-1487412840181-b39ce5fa3ac9?w=600&q=80&auto=format&fit=crop',
        isPopular: true,
        badge: 'Popular',
    },
    {
        id: 'thread-upper-lip',
        name: 'Upper Lip Threading',
        category: 'Threading',
        description: 'Quick and effective upper lip hair removal using threading for a smooth finish.',
        price: '$8',
        duration: '5 mins',
        benefits: ['Fast & Precise', 'No Irritation', 'All Skin Types'],
        image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'thread-chin',
        name: 'Chin Threading',
        category: 'Threading',
        description: 'Targeted chin hair removal with threading for a clean, smooth appearance.',
        price: '$8',
        duration: '5 mins',
        benefits: ['Precise', 'Gentle', 'No Chemicals'],
        image: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'thread-forehead',
        name: 'Forehead Threading',
        category: 'Threading',
        description: 'Removes unwanted forehead hair and refines the hairline with threading.',
        price: '$10',
        duration: '5 mins',
        benefits: ['Hairline Definition', 'Smooth Finish', 'No Redness'],
        image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'thread-full-face',
        name: 'Full Face Threading',
        category: 'Threading',
        description: 'Complete facial hair removal covering brows, upper lip, chin, cheeks, and forehead.',
        price: '$35',
        duration: '25 mins',
        benefits: ['Full Coverage', 'Defined Look', 'Best Value'],
        image: 'https://images.unsplash.com/photo-1552058544-f2b08422138a?w=600&q=80&auto=format&fit=crop',
        isPopular: true,
        badge: 'Best Value',
    },

    // ── WAXING ─────────────────────────────────────────────────────────────────
    {
        id: 'wax-eyebrow',
        name: 'Eyebrow Wax',
        category: 'Waxing',
        description: 'Clean eyebrow shaping using warm wax for smooth, defined brows.',
        price: '$15',
        duration: '10 mins',
        benefits: ['Neat Shape', 'Smooth Finish', 'Quick Service'],
        image: 'https://images.unsplash.com/photo-1487412840181-b39ce5fa3ac9?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'wax-upper-lip',
        name: 'Upper Lip Wax',
        category: 'Waxing',
        description: 'Gentle upper lip waxing for a clean, smooth finish that lasts weeks.',
        price: '$10',
        duration: '5 mins',
        benefits: ['Smooth Skin', 'Long-Lasting', 'Gentle Formula'],
        image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'wax-underarm',
        name: 'Underarm Wax',
        category: 'Waxing',
        description: 'Effective underarm waxing using premium hard wax for clean, smooth results.',
        price: '$20',
        duration: '15 mins',
        benefits: ['Smooth Underarms', '3–4 Week Results', 'Hard Wax Formula'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'wax-half-leg',
        name: 'Half Leg Wax',
        category: 'Waxing',
        description: 'Waxing from the knee down for smooth, hair-free lower legs.',
        price: '$35',
        duration: '25 mins',
        benefits: ['Knee to Ankle', 'Finer Regrowth', 'Long-Lasting'],
        image: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'wax-full-leg',
        name: 'Full Leg Wax',
        category: 'Waxing',
        description: 'Complete full-leg waxing from ankle to upper thigh for silky smooth results.',
        price: '$55',
        duration: '35 mins',
        benefits: ['Full Leg Coverage', 'Silky Smooth', '4–6 Week Results'],
        image: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=600&q=80&auto=format&fit=crop',
        isPopular: true,
        badge: 'Popular',
    },
    {
        id: 'wax-bikini',
        name: 'Bikini Wax',
        category: 'Waxing',
        description: 'Bikini line waxing for a clean, tidy finish using premium hard wax.',
        price: '$30',
        duration: '20 mins',
        benefits: ['Clean Lines', 'Hard Wax', 'Gentle & Safe'],
        image: 'https://images.unsplash.com/photo-1554188248-986adbb73be4?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'wax-brazilian',
        name: 'Brazilian Wax',
        category: 'Waxing',
        description: 'Full Brazilian waxing using premium hard wax for complete removal with lasting results.',
        price: '$55',
        duration: '30 mins',
        benefits: ['Complete Coverage', 'Hard Wax Formula', '4–6 Week Results'],
        image: 'https://images.unsplash.com/photo-1554188248-986adbb73be4?w=600&q=80&auto=format&fit=crop',
        isPopular: true,
        badge: 'Popular',
    },
    {
        id: 'wax-back',
        name: 'Back Wax',
        category: 'Waxing',
        description: 'Full back waxing for men and women for a smooth, clean finish.',
        price: '$50',
        duration: '30 mins',
        benefits: ['Full Back Coverage', 'Smooth Finish', 'Men & Women'],
        image: 'https://images.unsplash.com/photo-1519824145371-296894a0daa9?w=600&q=80&auto=format&fit=crop',
    },

    // ── NUFREE ORGANIC WAXING ──────────────────────────────────────────────────
    {
        id: 'nufree-eyebrow',
        name: 'Eyebrow Nufree',
        category: 'Nufree Waxing',
        description: 'Organic, botanical Nufree formula for eyebrow shaping — ideal for sensitive skin.',
        price: '$18',
        duration: '10 mins',
        benefits: ['Botanical Formula', 'Sensitive Skin Safe', 'No Wax Residue'],
        image: 'https://images.unsplash.com/photo-1487412840181-b39ce5fa3ac9?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'nufree-upper-lip',
        name: 'Upper Lip Nufree',
        category: 'Nufree Waxing',
        description: 'Gentle Nufree organic hair removal for the upper lip — no irritation, no redness.',
        price: '$12',
        duration: '5 mins',
        benefits: ['Zero Irritation', 'Organic', 'No Redness'],
        image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'nufree-full-face',
        name: 'Full Face Nufree',
        category: 'Nufree Waxing',
        description: 'Complete facial Nufree hair removal — ideal for sensitive or reactive skin types.',
        price: '$48',
        duration: '30 mins',
        benefits: ['Full Coverage', 'Hypoallergenic', 'Botanical Formula'],
        image: 'https://images.unsplash.com/photo-1552058544-f2b08422138a?w=600&q=80&auto=format&fit=crop',
        isPopular: true,
        badge: 'Organic',
    },
    {
        id: 'nufree-underarm',
        name: 'Underarm Nufree',
        category: 'Nufree Waxing',
        description: 'Organic underarm hair removal using Nufree — perfect for sensitive skin.',
        price: '$28',
        duration: '15 mins',
        benefits: ['No Irritation', 'Organic', 'Sensitive Skin Safe'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'nufree-brazilian',
        name: 'Brazilian Nufree',
        category: 'Nufree Waxing',
        description: 'Full Brazilian using organic Nufree formula — the gentlest option for intimate hair removal.',
        price: '$65',
        duration: '35 mins',
        benefits: ['Organic Formula', 'Gentle & Thorough', 'Minimal Discomfort'],
        image: 'https://images.unsplash.com/photo-1554188248-986adbb73be4?w=600&q=80&auto=format&fit=crop',
        isPopular: true,
        badge: 'Best Organic',
    },

    // ── FACIAL TREATMENTS ─────────────────────────────────────────────────────
    {
        id: 'facial-classic',
        name: 'Classic Facial',
        category: 'Facial Treatments',
        description: 'A relaxing cleanse, exfoliation, toning, and moisturizing treatment for all skin types.',
        price: '$75',
        duration: '60 mins',
        benefits: ['Deep Cleanse', 'Hydrating', 'All Skin Types'],
        image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'facial-deep-cleanse',
        name: 'Deep Cleansing Facial',
        category: 'Facial Treatments',
        description: 'Thorough cleanse, steam, manual extraction, and masque to clear pores and balance skin.',
        price: '$85',
        duration: '60 mins',
        benefits: ['Removes Impurities', 'Clears Pores', 'Balanced Skin'],
        image: 'https://images.unsplash.com/photo-1556228720-da8e3810ee7f?w=600&q=80&auto=format&fit=crop',
        isPopular: true,
        badge: 'Popular',
    },
    {
        id: 'facial-hydra',
        name: 'HydraFacial',
        category: 'Facial Treatments',
        description: 'Multi-step vortex cleanse, exfoliation, extraction, and hydration infusion for instant glow with no downtime.',
        price: '$150',
        duration: '60 mins',
        benefits: ['Instant Glow', 'Deep Hydration', 'Pore Refinement'],
        image: 'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600&q=80&auto=format&fit=crop',
        isPopular: true,
        badge: 'Signature',
    },
    {
        id: 'facial-microderm',
        name: 'Microdermabrasion',
        category: 'Facial Treatments',
        description: 'Diamond-tip resurfacing that polishes away dull skin to reveal a smoother, brighter complexion.',
        price: '$95',
        duration: '50 mins',
        benefits: ['Skin Polishing', 'Texture Improvement', 'Brightening'],
        image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'facial-dermaplaning',
        name: 'Dermaplaning',
        category: 'Facial Treatments',
        description: 'Blade exfoliation removing peach fuzz and dead skin for an ultra-smooth, luminous surface.',
        price: '$85',
        duration: '45 mins',
        benefits: ['Removes Peach Fuzz', 'Silky Smooth', 'Better Product Absorption'],
        image: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'facial-microneedle',
        name: 'Microneedling',
        category: 'Facial Treatments',
        description: 'Collagen-induction therapy using micro-channels to reduce scars, fine lines, and improve skin texture.',
        price: '$175',
        duration: '75 mins',
        benefits: ['Collagen Boost', 'Scar Reduction', 'Anti-Aging'],
        image: 'https://images.unsplash.com/photo-1576426863848-c21f53c60b19?w=600&q=80&auto=format&fit=crop',
        isPopular: true,
        badge: 'Anti-Aging',
    },

    // ── LASER HAIR REMOVAL ────────────────────────────────────────────────────
    {
        id: 'laser-upper-lip',
        name: 'Laser – Upper Lip',
        category: 'Laser Hair Removal',
        description: 'Diode laser targeting the upper lip for permanently smooth, hair-free skin.',
        price: '$35',
        duration: '10 mins',
        benefits: ['Permanent Results', 'Cryo-Cooling', 'All Skin Types'],
        image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'laser-chin',
        name: 'Laser – Chin',
        category: 'Laser Hair Removal',
        description: 'Targeted chin laser hair removal for a permanently clean, smooth result.',
        price: '$35',
        duration: '10 mins',
        benefits: ['Precise', 'Cryo-Cooling', 'Long-Lasting'],
        image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'laser-full-face',
        name: 'Laser – Full Face',
        category: 'Laser Hair Removal',
        description: 'Complete facial laser hair removal covering cheeks, chin, upper lip, and sideburns.',
        price: '$120',
        duration: '30 mins',
        benefits: ['Full Face Coverage', 'Permanent Results', 'All Skin Tones'],
        image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=600&q=80&auto=format&fit=crop',
        isPopular: true,
        badge: 'Popular',
    },
    {
        id: 'laser-underarm',
        name: 'Laser – Underarm',
        category: 'Laser Hair Removal',
        description: 'Permanent underarm laser hair removal using medical-grade diode laser technology.',
        price: '$45',
        duration: '15 mins',
        benefits: ['Permanent', 'Quick Session', 'All Skin Types'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'laser-half-leg',
        name: 'Laser – Half Leg',
        category: 'Laser Hair Removal',
        description: 'Diode laser hair removal from the knee down for permanently smooth lower legs.',
        price: '$150',
        duration: '40 mins',
        benefits: ['Knee to Ankle', 'Long-Lasting', 'Smooth Skin'],
        image: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'laser-full-leg',
        name: 'Laser – Full Leg',
        category: 'Laser Hair Removal',
        description: 'Full-leg permanent laser hair removal from ankle to upper thigh.',
        price: '$250',
        duration: '60 mins',
        benefits: ['Full Coverage', 'Permanent Results', 'Time-Saving'],
        image: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=600&q=80&auto=format&fit=crop',
        isPopular: true,
        badge: 'Popular',
    },
    {
        id: 'laser-brazilian',
        name: 'Laser – Brazilian',
        category: 'Laser Hair Removal',
        description: 'Full Brazilian laser hair removal with clinical comfort and permanent, lasting results.',
        price: '$129',
        duration: '30 mins',
        benefits: ['Complete Coverage', 'Private & Discreet', 'Permanent'],
        image: 'https://images.unsplash.com/photo-1532274402911-5a369e4c4bb5?w=600&q=80&auto=format&fit=crop',
        isPopular: true,
        badge: 'Bestseller',
    },
    {
        id: 'laser-full-body',
        name: 'Laser – Full Body',
        category: 'Laser Hair Removal',
        description: 'Complete full-body laser hair removal across all areas in one comprehensive session.',
        price: '$599',
        duration: '90 mins',
        benefits: ['All Body Areas', 'Best Value', 'Maximum Savings'],
        image: 'https://images.unsplash.com/photo-1519824145371-296894a0daa9?w=600&q=80&auto=format&fit=crop',
        badge: 'Best Value',
    },
];

export const WHATSAPP_NUMBER = '16478904871';
