import { Service } from '../types';

export const SERVICES: Service[] = [

    // ── THREADING ──────────────────────────────────────────────────────────────
    {
        id: 'thread-eyebrow',
        name: 'Eyebrow Threading',
        category: 'Threading',
        description: 'Precise eyebrow shaping using traditional threading for clean, defined brows.',
        price: '$4',
        duration: '15 mins',
        benefits: ['Clean Shape', 'Long-Lasting', 'No Chemicals'],
        image: 'https://images.unsplash.com/photo-1487412840181-b39ce5fa3ac9?w=600&q=80&auto=format&fit=crop',
        isPopular: true,
        badge: 'Popular',
    },
    {
        id: 'thread-upper-lip',
        name: 'Upper Lip Threading',
        category: 'Threading',
        description: 'Quick and effective upper lip hair removal using threading for a smooth finish.',
        price: '$3',
        duration: '5 mins',
        benefits: ['Fast & Precise', 'No Irritation', 'All Skin Types'],
        image: 'https://images.unsplash.com/photo-1487412840181-b39ce5fa3ac9?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'thread-chin',
        name: 'Chin Threading',
        category: 'Threading',
        description: 'Targeted chin hair removal with threading for a clean, smooth appearance.',
        price: '$3',
        duration: '5 mins',
        benefits: ['Precise', 'Gentle', 'No Chemicals'],
        image: 'https://images.unsplash.com/photo-1487412840181-b39ce5fa3ac9?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'thread-forehead',
        name: 'Forehead Threading',
        category: 'Threading',
        description: 'Removes unwanted forehead hair and refines the hairline with threading.',
        price: '$3',
        duration: '5 mins',
        benefits: ['Hairline Definition', 'Smooth Finish', 'No Redness'],
        image: 'https://images.unsplash.com/photo-1487412840181-b39ce5fa3ac9?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'thread-full-face',
        name: 'Full Face Threading',
        category: 'Threading',
        description: 'Complete facial hair removal covering brows, upper lip, chin, cheeks, and forehead.',
        price: '$20',
        duration: '20 mins',
        benefits: ['Full Coverage', 'Defined Look', 'Best Value'],
        image: 'https://images.unsplash.com/photo-1487412840181-b39ce5fa3ac9?w=600&q=80&auto=format&fit=crop',
        badge: 'Best Value',
    },

    // ── WAXING ─────────────────────────────────────────────────────────────────
    {
        id: 'wax-eyebrow',
        name: 'Eyebrow Wax',
        category: 'Waxing',
        description: 'Clean eyebrow shaping using warm wax for smooth, defined brows.',
        price: '$8',
        duration: '10 mins',
        benefits: ['Neat Shape', 'Smooth Finish', 'Quick Service'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'wax-upper-lip',
        name: 'Upper Lip Wax',
        category: 'Waxing',
        description: 'Gentle upper lip waxing for a clean, smooth finish that lasts weeks.',
        price: '$4',
        duration: '5 mins',
        benefits: ['Smooth Skin', 'Long-Lasting', 'Gentle Formula'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'wax-chin',
        name: 'Chin Wax',
        category: 'Waxing',
        description: 'Effective chin hair removal using warm wax for a clean, smooth result.',
        price: '$4',
        duration: '5 mins',
        benefits: ['Precise', 'Smooth Finish', 'Long-Lasting'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'wax-face-sides',
        name: 'Face Sides Wax',
        category: 'Waxing',
        description: 'Waxing the sides of the face and sideburn area for a clean, defined look.',
        price: '$8',
        duration: '10 mins',
        benefits: ['Defined Jawline', 'Smooth Finish', 'Quick Service'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'wax-full-face',
        name: 'Full Face Wax',
        category: 'Waxing',
        description: 'Complete facial waxing covering all areas for a smooth, hair-free complexion.',
        price: '$20',
        duration: '20 mins',
        benefits: ['Full Coverage', 'Smooth Skin', 'Long-Lasting'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'wax-underarm',
        name: 'Underarm Wax',
        category: 'Waxing',
        description: 'Effective underarm waxing using premium hard wax for clean, smooth results.',
        price: '$7',
        duration: '5 mins',
        benefits: ['Smooth Underarms', '3–4 Week Results', 'Hard Wax Formula'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'wax-half-arms',
        name: 'Half Arms Wax',
        category: 'Waxing',
        description: 'Waxing from the elbow to the wrist for smooth, hair-free forearms.',
        price: '$15',
        duration: '20 mins',
        benefits: ['Elbow to Wrist', 'Finer Regrowth', 'Smooth Skin'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'wax-arms',
        name: 'Full Arms Wax',
        category: 'Waxing',
        description: 'Complete arm waxing from shoulder to wrist for silky smooth skin.',
        price: '$20',
        duration: '20 mins',
        benefits: ['Full Arm Coverage', 'Silky Smooth', 'Long-Lasting'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'wax-half-back',
        name: 'Half Back Wax',
        category: 'Waxing',
        description: 'Upper or lower back waxing for targeted, smooth results.',
        price: '$15',
        duration: '15 mins',
        benefits: ['Targeted', 'Smooth Finish', 'Quick Service'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'wax-full-back',
        name: 'Full Back Wax',
        category: 'Waxing',
        description: 'Complete back waxing for a smooth, hair-free finish from shoulders to lower back.',
        price: '$25',
        duration: '30 mins',
        benefits: ['Full Back Coverage', 'Smooth Finish', 'Long-Lasting'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'wax-full-front',
        name: 'Full Front Wax',
        category: 'Waxing',
        description: 'Complete front body waxing for a smooth, clean finish.',
        price: '$15',
        duration: '30 mins',
        benefits: ['Full Front Coverage', 'Smooth Skin', 'Long-Lasting'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'wax-buttocks',
        name: 'Buttocks Wax',
        category: 'Waxing',
        description: 'Gentle buttocks waxing for a smooth, clean result using premium wax.',
        price: '$10',
        duration: '10 mins',
        benefits: ['Smooth Finish', 'Gentle Formula', 'Long-Lasting'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'wax-half-leg',
        name: 'Half Legs Wax',
        category: 'Waxing',
        description: 'Waxing from the knee down for smooth, hair-free lower legs.',
        price: '$20',
        duration: '20 mins',
        benefits: ['Knee to Ankle', 'Finer Regrowth', 'Long-Lasting'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'wax-full-leg',
        name: 'Full Legs Wax',
        category: 'Waxing',
        description: 'Complete full-leg waxing from ankle to upper thigh for silky smooth results.',
        price: '$30',
        duration: '30 mins',
        benefits: ['Full Leg Coverage', 'Silky Smooth', '4–6 Week Results'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
        isPopular: true,
        badge: 'Popular',
    },
    {
        id: 'wax-full-body',
        name: 'Full Body Wax',
        category: 'Waxing',
        description: 'Comprehensive full-body waxing covering all areas for a head-to-toe smooth finish.',
        price: '$135',
        duration: '2 hrs',
        benefits: ['All Body Areas', 'Maximum Savings', 'Head-to-Toe Smooth'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
        badge: 'Best Value',
    },
    {
        id: 'wax-mens-half-arms',
        name: "Men's Half Arms Wax",
        category: 'Waxing',
        description: "Men's half arm waxing for smooth, hair-free forearms.",
        price: '$30',
        duration: '30 mins',
        benefits: ['Elbow to Wrist', 'Smooth Finish', 'Long-Lasting'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'wax-mens-lower-legs',
        name: "Men's Half Lower Legs Wax",
        category: 'Waxing',
        description: "Men's lower leg waxing for smooth, clean skin from the knee down.",
        price: '$40',
        duration: '30 mins',
        benefits: ['Knee to Ankle', 'Smooth Skin', 'Finer Regrowth'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'wax-mens-chest',
        name: "Men's Chest Wax",
        category: 'Waxing',
        description: "Men's chest waxing for a smooth, clean finish using premium wax.",
        price: '$45',
        duration: '30 mins',
        benefits: ['Smooth Chest', 'Long-Lasting', 'Premium Wax'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'wax-mens-full-back',
        name: "Men's Full Back Wax",
        category: 'Waxing',
        description: "Men's full back waxing for a smooth, hair-free finish from shoulders to lower back.",
        price: '$45',
        duration: '30 mins',
        benefits: ['Full Back Coverage', 'Smooth Finish', 'Long-Lasting'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },

    // ── NUFREE WAXING ──────────────────────────────────────────────────────────
    {
        id: 'nufree-upper-lip',
        name: 'Upper Lip Nufree Wax',
        category: 'Nufree Waxing',
        description: 'Gentle Nufree organic hair removal for the upper lip — no irritation, no redness.',
        price: '$6',
        duration: '5 mins',
        benefits: ['Zero Irritation', 'Organic Formula', 'No Redness'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'nufree-chin',
        name: 'Chin Nufree Wax',
        category: 'Nufree Waxing',
        description: 'Organic Nufree chin hair removal for a clean, smooth result with no irritation.',
        price: '$6',
        duration: '5 mins',
        benefits: ['Botanical Formula', 'Sensitive Skin Safe', 'Smooth Finish'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'nufree-face-sides',
        name: 'Face Sides Nufree Wax',
        category: 'Nufree Waxing',
        description: 'Organic Nufree hair removal for the sides of the face, gentle enough for sensitive skin.',
        price: '$12',
        duration: '10 mins',
        benefits: ['Gentle on Skin', 'Organic', 'Defined Jawline'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'nufree-full-face',
        name: 'Full Face Nufree Wax',
        category: 'Nufree Waxing',
        description: 'Complete facial Nufree hair removal — ideal for sensitive or reactive skin types.',
        price: '$28',
        duration: '20 mins',
        benefits: ['Full Coverage', 'Hypoallergenic', 'Botanical Formula'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
        isPopular: true,
        badge: 'Organic',
    },
    {
        id: 'nufree-underarm',
        name: 'Underarms Nufree Wax',
        category: 'Nufree Waxing',
        description: 'Organic underarm hair removal using Nufree — perfect for sensitive skin.',
        price: '$10',
        duration: '10 mins',
        benefits: ['No Irritation', 'Organic', 'Sensitive Skin Safe'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'nufree-half-arms',
        name: 'Half Arms Nufree Wax',
        category: 'Nufree Waxing',
        description: 'Organic Nufree half arm hair removal for smooth, irritation-free forearms.',
        price: '$30',
        duration: '20 mins',
        benefits: ['Elbow to Wrist', 'Organic Formula', 'Smooth Skin'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'nufree-full-arms',
        name: 'Full Arms Nufree Wax',
        category: 'Nufree Waxing',
        description: 'Complete arm hair removal using organic Nufree formula from shoulder to wrist.',
        price: '$40',
        duration: '30 mins',
        benefits: ['Full Coverage', 'Organic', 'Long-Lasting'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'nufree-bikini-line',
        name: 'Bikini Line Nufree Wax',
        category: 'Nufree Waxing',
        description: 'Organic Nufree bikini line hair removal for clean, gentle results on sensitive skin.',
        price: '$25',
        duration: '15 mins',
        benefits: ['Clean Lines', 'Gentle & Safe', 'Organic Formula'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'nufree-extended-bikini',
        name: 'Extended Bikini Nufree Wax',
        category: 'Nufree Waxing',
        description: 'Extended bikini area organic Nufree wax for a thorough, gentle clean.',
        price: '$35',
        duration: '20 mins',
        benefits: ['Extended Coverage', 'Organic', 'Minimal Discomfort'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'nufree-brazilian',
        name: 'Brazilian Nufree Wax',
        category: 'Nufree Waxing',
        description: 'Full Brazilian using organic Nufree formula — the gentlest option for intimate hair removal.',
        price: '$50',
        duration: '20 mins',
        benefits: ['Organic Formula', 'Gentle & Thorough', 'Minimal Discomfort'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
        isPopular: true,
        badge: 'Best Organic',
    },
    {
        id: 'nufree-full-legs',
        name: 'Full Legs Nufree Wax',
        category: 'Nufree Waxing',
        description: 'Complete full-leg hair removal using organic Nufree formula for silky, smooth results.',
        price: '$60',
        duration: '45 mins',
        benefits: ['Full Leg Coverage', 'Organic', 'Silky Smooth'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'nufree-full-body',
        name: 'Full Body Nufree Wax',
        category: 'Nufree Waxing',
        description: 'Comprehensive full-body organic Nufree hair removal for a head-to-toe smooth, gentle finish.',
        price: '$299',
        duration: '2 hrs 30 mins',
        benefits: ['All Body Areas', 'Premium Organic', 'Head-to-Toe Smooth'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
        badge: 'Premium',
    },

    // ── FACIAL TREATMENTS ─────────────────────────────────────────────────────
    {
        id: 'facial-express',
        name: 'Express Deep Cleansing Facial',
        category: 'Facial Treatments',
        description: 'A refreshing facial designed to deeply cleanse the skin, remove impurities, and unclog pores. Includes cleansing, exfoliation, gentle extractions, and a soothing mask to restore balance and hydration. Perfect for maintaining healthy, clear, and refreshed skin.',
        price: '$40',
        duration: '30 mins',
        benefits: ['Deep Cleanse', 'Unclogs Pores', 'Refreshed Skin'],
        image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'facial-classic',
        name: "Classic Fernanda's Facial",
        category: 'Facial Treatments',
        description: 'A relaxing and rejuvenating facial designed to cleanse, exfoliate, and nourish the skin. This treatment includes deep cleansing, gentle exfoliation, extractions if needed, facial massage, and a customized mask selected for your skin type. Helps improve skin texture, restore hydration, and leave the skin refreshed, balanced, and glowing.',
        price: '$60',
        duration: '1 hr',
        benefits: ['Deep Cleanse', 'Hydrating', 'All Skin Types'],
        image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'facial-microderm',
        name: 'Microdermabrasion Skin Renewal',
        category: 'Facial Treatments',
        description: 'A non-invasive exfoliation treatment that removes dead skin cells and stimulates new skin growth. Helps improve skin texture, reduce fine lines, acne scars, and uneven skin tone. Leaves the skin smoother, brighter, and more refreshed with little to no downtime.',
        price: '$99',
        duration: '1 hr 15 mins',
        benefits: ['Skin Polishing', 'Texture Improvement', 'Brightening'],
        image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'facial-dermaplaning',
        name: 'Dermaplaning Facial',
        category: 'Facial Treatments',
        description: 'A gentle exfoliating treatment that removes dead skin cells and fine facial hair using a specialized blade. Helps improve skin texture, enhance product absorption, and create a smoother, brighter complexion.',
        price: '$75',
        duration: '1 hr 15 mins',
        benefits: ['Removes Peach Fuzz', 'Silky Smooth', 'Better Product Absorption'],
        image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'facial-microneedle',
        name: 'Microneedling (Collagen Induction Therapy)',
        category: 'Facial Treatments',
        description: 'Collagen-induction therapy using micro-channels to reduce scars, fine lines, and improve skin texture.',
        price: '$175 / 3 for $400',
        duration: '1 hr',
        benefits: ['Collagen Boost', 'Scar Reduction', 'Anti-Aging'],
        image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80&auto=format&fit=crop',
        isPopular: true,
        badge: 'Anti-Aging',
    },
    {
        id: 'facial-korean',
        name: 'Korean Glow Facial',
        category: 'Facial Treatments',
        description: 'Experience the secrets of Korean skincare with this multi-step facial designed to restore hydration, brighten the complexion, and promote healthy glowing skin. Includes deep cleansing, gentle exfoliation, nourishing serums, and hydrating masks.',
        price: '$85',
        duration: '1 hr',
        benefits: ['Intense Hydration', 'Brightening', 'Healthy Glow'],
        image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'facial-skeyndor',
        name: 'Skeyndor Essential Facial',
        category: 'Facial Treatments',
        description: 'A professional facial designed to cleanse, hydrate, and refresh the skin while improving overall texture and radiance. Helps remove impurities, restore moisture balance, and promote a healthy, glowing complexion.',
        price: '$75',
        duration: '1 hr',
        benefits: ['Deep Hydration', 'Removes Impurities', 'Healthy Glow'],
        image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'facial-radiance',
        name: 'Radiance Brightening Facial',
        category: 'Facial Treatments',
        description: 'A powerful skin-brightening treatment using advanced nano needling to enhance absorption of professional brightening serums and exosomes. Targets pigmentation, uneven skin tone, and dullness while improving overall skin texture and glow.',
        price: '$130',
        duration: '1 hr 30 mins',
        benefits: ['Targets Pigmentation', 'Even Skin Tone', 'Luminous Glow'],
        image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80&auto=format&fit=crop',
        isPopular: true,
        badge: 'Brightening',
    },
    {
        id: 'facial-exosomes',
        name: 'Exosomes Anti-Aging Facial',
        category: 'Facial Treatments',
        description: 'An advanced anti-aging facial designed to restore, repair, and rejuvenate the skin using nano needling and powerful exosomes. Targets fine lines, wrinkles, loss of firmness, and dull skin.',
        price: '$145',
        duration: '1 hr 30 mins',
        benefits: ['Reduces Fine Lines', 'Restores Firmness', 'Skin Rejuvenation'],
        image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80&auto=format&fit=crop',
        badge: 'Anti-Aging',
    },
    {
        id: 'facial-hydra',
        name: 'HydraFacial Treatment',
        category: 'Facial Treatments',
        description: 'A luxury multi-step skin treatment designed to deeply cleanse, exfoliate, and intensely hydrate the skin. Includes hydro-dermabrasion, oxygen infusion, microcurrent for lifting and toning, and LED therapy. Suitable for all skin types.',
        price: '$120',
        duration: '1 hr 30 mins',
        benefits: ['Instant Glow', 'Deep Hydration', 'Pore Refinement'],
        image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80&auto=format&fit=crop',
        isPopular: true,
        badge: 'Signature',
    },
    {
        id: 'facial-eyebrow-tint',
        name: 'Eyebrow Tint',
        category: 'Facial Treatments',
        description: 'Enhance the color and definition of your natural brows using a semi-permanent tint. Results typically last 2–4 weeks.',
        price: '$10',
        duration: '10 mins',
        benefits: ['Defined Brows', 'Semi-Permanent Color', 'Lasts 2–4 Weeks'],
        image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80&auto=format&fit=crop',
    },

    // ── LASER HAIR REMOVAL ────────────────────────────────────────────────────
    // Small Areas
    {
        id: 'laser-upper-lip',
        name: 'Laser – Upper Lip',
        category: 'Laser Hair Removal',
        description: 'Diode laser targeting the upper lip for permanently smooth, hair-free skin.',
        price: '$35',
        duration: '10 mins',
        benefits: ['Permanent Results', 'Cryo-Cooling', 'All Skin Types'],
        image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'laser-chin',
        name: 'Laser – Chin',
        category: 'Laser Hair Removal',
        description: 'Targeted chin laser hair removal for a permanently clean, smooth result.',
        price: '$35 & up',
        duration: '10 mins',
        benefits: ['Precise', 'Cryo-Cooling', 'Long-Lasting'],
        image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'laser-lip-chin',
        name: 'Laser – Lip & Chin',
        category: 'Laser Hair Removal',
        description: 'Combined upper lip and chin laser treatment for a fully smooth lower face.',
        price: '$69',
        duration: '15 mins',
        benefits: ['Combo Saving', 'Precise', 'Long-Lasting'],
        image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80&auto=format&fit=crop',
        isPopular: true,
        badge: 'Popular',
    },
    {
        id: 'laser-neck',
        name: 'Laser – Neck',
        category: 'Laser Hair Removal',
        description: 'Smooth, hair-free neck using medical-grade diode laser with permanent results.',
        price: '$39',
        duration: '10 mins',
        benefits: ['Permanent', 'Gentle', 'Quick Session'],
        image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'laser-face-sides',
        name: 'Laser – Face Sides',
        category: 'Laser Hair Removal',
        description: 'Laser hair removal targeting the sides of the face and sideburn area.',
        price: '$59',
        duration: '15 mins',
        benefits: ['Defined Jawline', 'Permanent', 'All Skin Tones'],
        image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80&auto=format&fit=crop',
    },
    // Full Face
    {
        id: 'laser-full-face',
        name: 'Laser – Full Face',
        category: 'Laser Hair Removal',
        description: 'Complete facial laser hair removal covering cheeks, chin, upper lip, and sideburns.',
        price: '$120',
        duration: '30 mins',
        benefits: ['Full Face Coverage', 'Permanent Results', 'All Skin Tones'],
        image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=600&q=80&auto=format&fit=crop',
        isPopular: true,
        badge: 'Popular',
    },
    // Upper Body
    {
        id: 'laser-underarm',
        name: 'Laser – Underarms',
        category: 'Laser Hair Removal',
        description: 'Permanent underarm laser hair removal using medical-grade diode laser technology.',
        price: '$35',
        duration: '15 mins',
        benefits: ['Permanent', 'Quick Session', 'All Skin Types'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'laser-half-arms',
        name: 'Laser – Half Arms',
        category: 'Laser Hair Removal',
        description: 'Laser hair removal from elbow to wrist for smooth, permanently hair-free forearms.',
        price: '$79',
        duration: '25 mins',
        benefits: ['Smooth Arms', 'Permanent', 'Medical-Grade Laser'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'laser-full-arms',
        name: 'Laser – Full Arms',
        category: 'Laser Hair Removal',
        description: 'Complete arm laser hair removal from shoulder to wrist for lasting smooth skin.',
        price: '$99',
        duration: '35 mins',
        benefits: ['Full Coverage', 'Permanent', 'All Skin Types'],
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'laser-chest',
        name: 'Laser – Chest',
        category: 'Laser Hair Removal',
        description: 'Medical-grade laser hair removal for the chest area with lasting results.',
        price: '$149',
        duration: '30 mins',
        benefits: ['Permanent', 'Precise', 'Men & Women'],
        image: 'https://images.unsplash.com/photo-1519824145371-296894a0daa9?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'laser-shoulders',
        name: 'Laser – Shoulders',
        category: 'Laser Hair Removal',
        description: 'Permanent laser hair removal targeting the shoulder area for a clean, smooth result.',
        price: '$99',
        duration: '25 mins',
        benefits: ['Permanent', 'Smooth Finish', 'All Skin Types'],
        image: 'https://images.unsplash.com/photo-1519824145371-296894a0daa9?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'laser-full-back',
        name: 'Laser – Full Back',
        category: 'Laser Hair Removal',
        description: 'Complete full back laser hair removal for a smooth, hair-free finish.',
        price: '$149',
        duration: '40 mins',
        benefits: ['Full Back Coverage', 'Permanent', 'Men & Women'],
        image: 'https://images.unsplash.com/photo-1519824145371-296894a0daa9?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'laser-half-back',
        name: 'Laser – Half Back',
        category: 'Laser Hair Removal',
        description: 'Upper or lower back laser hair removal for targeted permanent results.',
        price: '$99',
        duration: '25 mins',
        benefits: ['Targeted', 'Permanent', 'Medical-Grade'],
        image: 'https://images.unsplash.com/photo-1519824145371-296894a0daa9?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'laser-stomach',
        name: 'Laser – Stomach',
        category: 'Laser Hair Removal',
        description: 'Stomach area laser hair removal for permanently smooth, confident skin.',
        price: '$99',
        duration: '25 mins',
        benefits: ['Permanent', 'Precise', 'All Skin Types'],
        image: 'https://images.unsplash.com/photo-1519824145371-296894a0daa9?w=600&q=80&auto=format&fit=crop',
    },
    // Lower Body
    {
        id: 'laser-bikini-line',
        name: 'Laser – Bikini Line',
        category: 'Laser Hair Removal',
        description: 'Clean bikini line laser hair removal with permanent, lasting results.',
        price: '$89',
        duration: '20 mins',
        benefits: ['Clean Lines', 'Permanent', 'Gentle & Safe'],
        image: 'https://images.unsplash.com/photo-1532274402911-5a369e4c4bb5?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'laser-brazilian',
        name: 'Laser – Brazilian',
        category: 'Laser Hair Removal',
        description: 'Full Brazilian laser hair removal with clinical comfort and permanent, lasting results.',
        price: '$129',
        duration: '30 mins',
        benefits: ['Complete Coverage', 'Private & Discreet', 'Permanent'],
        image: 'https://images.unsplash.com/photo-1532274402911-5a369e4c4bb5?w=600&q=80&auto=format&fit=crop',
        isPopular: true,
        badge: 'Bestseller',
    },
    {
        id: 'laser-half-leg',
        name: 'Laser – Half Legs',
        category: 'Laser Hair Removal',
        description: 'Diode laser hair removal from the knee down for permanently smooth lower legs.',
        price: '$119',
        duration: '35 mins',
        benefits: ['Knee to Ankle', 'Long-Lasting', 'Smooth Skin'],
        image: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=600&q=80&auto=format&fit=crop',
    },
    {
        id: 'laser-full-leg',
        name: 'Laser – Full Legs',
        category: 'Laser Hair Removal',
        description: 'Full-leg permanent laser hair removal from ankle to upper thigh.',
        price: '$159',
        duration: '55 mins',
        benefits: ['Full Coverage', 'Permanent Results', 'Time-Saving'],
        image: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=600&q=80&auto=format&fit=crop',
        isPopular: true,
        badge: 'Popular',
    },
    // Full Body
    {
        id: 'laser-full-body',
        name: 'Laser – Full Body',
        category: 'Laser Hair Removal',
        description: 'Complete full-body laser hair removal across all areas in one comprehensive session.',
        price: '$599',
        duration: '90 mins',
        benefits: ['All Body Areas', 'Best Value', 'Maximum Savings'],
        image: 'https://images.unsplash.com/photo-1519824145371-296894a0daa9?w=600&q=80&auto=format&fit=crop',
        badge: 'Best Value',
    },
];

export const WHATSAPP_NUMBER = '16478904871';
